* entrance
A cleft in the rocks opens up into a round chamber about 20 feet across. There
are three doors in this chamber, but two are filled with rubble from collapsed ceilings.
** corridor A
The only exit from the entrance chamber leads to a corridor that comes to
an X intersection after about 10 feet or so.

*** relic chamber
After passing through a corridor about 100 meters long, you find yourselves in a
massive chamber. From what you can tell, it appears to be hexagonal.

At least 100 feet across, you are unable to determine the length or true shape
of the chamber for several reasons:

1) Most of the chamber is shrouded in darkness. You don't feel or sense any
   threat or danger from the darkness, it seems to be simply a case of "let's
   find the light switch".
2) A shimmering veil of energy prevents you from going more than 50 feet into
   the chamber, and the nature of the veil makes it harder to ascertain what's
   in the chamber.
3) The one thing you are able to make out quite clearly though, is the massive
   airship that takes up much of the chamber. It blocks out much of what lay
   behind it, further lending to your issues determining the size and shape of
   the chamber.

From what you can tell, the ship is in perfect condition. Roughly 80 feet wide
and you estimate that it's at least 200 feet long -- although the back half is
shrouded by darkness, making it hard to accurately determine the dimensions of
the vessel.



*** chamber 1
After travelling down a long corridor that makes strange 90 degree turns (
you're pretty sure you should have doubled back at least once or twice ), you
emerge into the next chamber.

A triangular chamber, with each side being 50 feet across... you think. It's
hard to get a good grasp of just how big this chamber is. There's a strange
echoing buzz, but you can't tell where it's coming from.

This room is full of what appear to be bean bag chairs and discarded toys.

Drifting through the air in the center of the chamber is a yellowish, hazy cloud.

The cloud is a [[file:~/Documents/CampaignNotes/Numenera-ThisOldShip/creature-stats.org::*Yellow Swarm 5 (15)][Yellow Swarm]], which will attack after a character gets close
enough to tell that they're insects ( read description, then call the attack ).

**** corridor B
A passage that runs for about 50 feet, slowly bending to the right until you've
made a 90 degree turn.

***** chamber 7
A rectangular chamber that's 30 feet across and 40 feet long.

Mostly filled with shelves and storage alcoves, this room appears to be a
warehouse of some kind. All the barrels and boxes you find are empty, except for
one. It contains a small colourful device about three feet across and two feet
high. The buttons have large and easy to read icons, almost like it was built
for a child. There is a hatch on one side that opens easily, with a 2x1.5 foot
chamber within.

Anything placed within the device has metallic googly eyes attached.

There are no other exits from this room.
*** shaft
After travelling down a corridor that descends for about 50 feet, you find
yourself entering another chamber.

You enter into a circular chamber about 90 feet across. Set into the ground is
an enormous shaft about 75 feet across. It's offset from the center of the
chamber, the wall opposite the door you entered has no ledge while there is
about 15 feet of solid ground from the door to the edge of the shaft. From the
entrance you can't see the bottom of the shaft.

Next to the door you entered through is a small rusty looking panel set into the
wall, not fully closed.

Fifteen feet further down is a machine built into the wall, with some cables
attached it that disappear over the side.

**** descriptions and stuff
***** the shaft
The shaft appears to be at least 200 meters tall ( about 650 feet ) deep. You
can see the bottom, just barely -- a small circle of light showing a chamber
deep below you. On the shaft walls, you can see at least three or four lit
platforms; potential other routes to explore?

***** broken machine
A piece of machinery has three synthcord cables tied to it, the other ends
disappear over the edge. Inspecting the synthcord reveals it was cut. The knots
where the synthcord was attached to the machine have some green threads caught
in the knots.

***** box near doorway
Set into the wall near the doorway is a small panel that isn't fully
shut. Opening it reveals a small box, inside of which is a rail of some kind
with a button.

Pressing the button causes the rail to advance forward, bringing forth from a
hidden compartment a strange oddly shaped device with a strap, hanging from a
hook on the conveyor.

Though oddly shaped, the device fits quite comfortably into your hand. You can't
tell if it's changing shape to fit your hand or not though -- it feels like it
shifts when you move your fingers around, but you don't see any movement when
you look at it.

Next to where your thumb rests are two buttons with strange sigils.

Within this chamber, pressing one of the buttons causes the device to slowly
rise, the other causes the device to slowly fall. To descend, you have to press
the button that lowers the device and step off the ledge into the shaft. The
device reduces gravity just for you within the shaft, causing you to fall quite
slowly down the shaft.

It's a level 3 might task to go to the bottom without slipping, while a level 5
intellect task allows the PC to figure out how to "steer".

**** exits along the side of the shaft
***** chamber 8
A rectangular chamber 30 feet across and 60 feet long.

The longer walls are covered in racks and shelves that contain thousands of
nodules. Each one produces a whispering susurrus that on its own is nothing but
noise, but when you step back the susurrus combines into a quiet voice that does
nothing but insult you in a unending string of expletives, curses, and remarks
about your mother.

Spread throughout the room area number of boxes and crates. An open one shows
even more of the strange devices.

In the center of the chamber a group of explorers have set up camp. Currently
they're all laying down, circled around a softly glowing numenera that you
recognize as a smokeless fire -- handy when you want heat or to cook while in a
ruin and don't want to worry about some ancient fire suppression system going
off.

Each of them is either wrapped in a green cloak or is using a green cloak for a
pillow.

There are three of them, although it looks like there are cots and supplies for
twice their number.

One of the ones left is the thief who stole from Mex & Pamki.

The group contains:

- the thief, a level 4 (12) nano
  health: 15  damage: 3  movement: short
  resists mental effects as level 4

  attacks with ice based esotaries from up to a long distance away

  if attacked, immediately casts an esotary that gives them 4 points of armour
  and causes 2 points of might damage to anyone that attacks them

  in addition to the loot they stole, they also have on them:
  - 4 shins
  - Teleporter (mass), level 2 (pg 94 in tech compendium)

- two explorers, level 4(12)
  health: 18  damage: 4  movement: short  armor: 2

  Try to stay at range and attack with pistols, will abandon the nano if made
  aware he stole from Pamki or Mex

  loot:
  - light pistol
  - light sword
  - explorers pack
  - 17 shins between the two of them
  - 2 oddities (a crystal antiprism about 4 inches across that is mildly
    repelled away from living flesh, and a human-faced insect trapped in a piece
    of amber)
  - a remote sensorium, level 3 (tech compendium, pg 85)

***** chamber 11
A circular chamber with a 30 foot diameter.

The walls and ceiling of the chamber is covered by a thick mat of some kind of
fungi you've never seen before. Purple with yellow and electric blue stippling,
the fungus produces odd patterns on the walls and ceiling. There are also many
large whorled growths, some on the ceiling nearly reach the ground. They fill
the chamber with a cinnamony musk.

Standing in the center of the chamber is a silver arch that twists once at the
apex of the arch. Each support is about 2 feet long and half a foot wide and
seems to maintain those dimensions for the entire length of the arch.

You notice that between the time you entered the chamber ( just moments ago )
and now, the temperature has begun to drop. Doesn't seem to be an issue right
now, though.

****** chamber features
******* the arch
One support of the arch has a set of five symbols, one of which is glowing. You
don't recognize any of the symbols at first glance. The other support has a
small chamber with a steelglass door with a handle.

Stepping through the arch removes one organ from a living creature. The organ
removed still all the parts and pieces it needs to be put into a living creature
of the same species, but the "donor" has their body changed to accomodate the
lost organ -- the esophagus gets connected directly to the intestines, the aorta
that would connect to the heart is simply closed off. Only removing the heart or
brain is immediately fatal (although quick thinking could save someone who had
their heart removed). Some organs can be removed without immediate death (
stomach, liver, etc ) although without them the creature will die
eventually. Others can be removed without issue ( except perhaps an inability is
gained, losing a lung makes it harder to do cardio stuff, losing a kidney makes
you more vulnerable to poisons, etc ).

Player who steps through rolls a d100, then from this chart you tell them what
they lost:

|  Roll | Organ         | Result                                           |
|-------+---------------+--------------------------------------------------|
|   1-5 | Tounge        | Any task requiring speech is hindered by two     |
|       |               |steps, and you can no longer taste food           |
|  6-10 | Eye           | Disadvantage on any searching, perception, or    |
|       |               |attack roles                                      |
| 11-15 | Hearing Bones | Deaf, can't hear anything, tasks requiring       |
|       |               |understanding speech hindered by two steps        |
| 16-20 | Kidney        | Disadvantage on saves vs poison or disease       |
| 21-40 | Lung          | Inability on tasks requiring cardio or holding   |
|       |               |your breath                                       |
| 41-60 | Stomach       | Eating solid food causes 1 point of might damage |
|       |               |for [1d10] hours, will slowly succumb to          |
|       |               |starvation over [1d20+10] days                    |
| 61-89 | Liver         |Goes down one step on the damage track every [1d4]|
|       |               | days, can't go back up damage track at all until |
|       |               |liver is replaced (by original or something else) |
| 90-99 | Heart         | You're unconcious, and will be dead in [1d10+5]  |
|       |               |minutes unless you get your heart back (or        |
|       |               |something that can pump blood for you)            |
|   100 | Brain         | You dead.                                        |

Replacing the organ requires either a difficulty 7 medical task, or a level 5
intellect task to change select the right symbol so the organ is put back. 

******* temperature
The temperature will continue to drop, slowly at first, but by the time they're
done inspecting things and playing around with the arch it should be noticiably
colder. Probably getting close to freezing.

The chamber will continue to cool, reaching a temperature far below 0 degrees.

It will stay that way for two hours, then very quickly revert to normal. This
doesn't happen again.

The fungus is affected by the cold; it will freeze completely solid.

Potential GM intrusion: if the players attempt to cross while the fungus is
frozen, they slip and hit one. It will explode, doing 4 points of Speed
damage that bypasses armor. There is a 50% chance this will set off other fungus
columns ( which will affect someone from the party at random -- assign everyone
a number and roll [1d5] ). Each other fungus that explodes has the same chance
to set off another explosion.
****** trapped exit
A door with a shining golden veil of energy preventing access further. Touching
the veil gives you a warm feeling.

A panel nearby can be used to open the door, a level 6 Intellect task. Failing
sets off a defense mechanism: All the doors in chamber 11 are sealed by panels,
and 5 small defense drones are released into the chamber. They act as a horde,
attacking whoever set off the trap.

If captured, the target is taken to Chamber 7

******* chamber 13
A hexagonal chamber 30 feet across.

The center of the chamber is occupied by a large metallic urn. Every 30-90
seconds a bubble drifts up from the urn. The bubbles are formed from a liquid
that creates strange refraction patterns on the surface of the bubble.

Each bubble emits psychic talk -- surprised and curious questions. These
questions continue until the bubble pops.

The wall to the right-hand side of the wall opposite the door you came in on is
covered by a gigantic three dimensional mural about a foot deep. The mural seems
to be made from grains of coloured sand that showly shift as the mural slowly
runs through a scene of a space battle of some kind.

After watching for a few repetitions, you realize that each time it's
different. It's almost like the creatures and ships react to what their opponent
did in the last repetition.

Touching the sand creates ripples, and seems to change the outcome of that repetition.

******** hidden exit
A section of the mural is always dark -- no ships, lasers, stars, planets, gas
clouds, or anything else seem to approach a section on the right of the
mural. This is actually a door covered by a darkfield emitter. 

********* chamber 14
A circular chamber with a radius of about 15 feet.

A device is built into a section of the wall opposite the door you come in. 

A murden is currently inspecting the device. It will step aside to allow you to
inspect the device, and if asked nicely will show you how it works. If attacked
will activate a cypher that instantly teleports it elsewhere.

The device is a blister of synth that seemingly grows from the wall. It has an
opening about three feet wide and two feet tall. On the left side of the
opening there is a lever, and below the lever is a button.

The device attaches a small nodule to any metallic object placed within the
device once the lever is pulled ( activates a force field over the hole ) and
the button is pushed.

Once attached, the nodule electrifies the metallic portion of the object for the
next [1d10] days. After the charge dissipates, the nodule falls off on its own.

Any creature hit by a weapon with the nodule attached must make a Level 4 Might
defense roll or be stunned for its next turn.

There are no other exits from this chamber.
******** accessway
Nearly hidden behind bundles of frayed wires, this accessway was built for
slightly shorter creatures -- humans have to duck their heads to avoid hitting
their heads on pipes and protuberances that extrude from the ceiling.
********* chamber 15
A rectangular chamber 30 feet across and 60 feet long.

The walls are covered in iconography and what looks like written instructions,
although you don't recognize the script.

Two rows of chair-pods stretch the length of the chamber. Both rows are oriented
so they open towards the center of the chamber. The pods are roughly ovoid, and
stand about six feet tall. The body of the pod is made from a highly reflective
metal, and the door seems to be made of some kind of crystal. Within the pod
there is a comfortable looking chair.

The pods don't seem to be built for humans; or at least not any humans you
recognize. Iconography on the walls of the chamber seem to indicate that the pods
are for a race of humans at least two feet taller than the average person today.

Sitting in a pod activates it, which induces sleep in the occupant. The pod
rises into the air and docks with a port set into the ceiling. For the next five
minutes, the pod emits lights and sounds before settling back to the ground.

Any human or human-enough creature that enters the pod gains +1 Intellect Edge
for the next 28 hours. The process doesn't seem to be repeatable.

There are no other exits from this chamber.
****** sealed exit A
A doorway filled with a jagged field of dark energy. Any creature that attempts
to touch the field or pass through takes 2 points of Intellect damage.

There is a panel that can be used to unlock the door, but the panel is broken,
leaving only what appears to be a key slot of some kind. (key is in chamber 16)
******* collapsed corridor 2
Filled with rubble, this corridor is impassible.

(if they insist on trying to clear it, gm intrusion to have the ceiling collapse
more, potentially trapping one of them)
****** sealed exit B
A doorway filled with a shimmering field that gently rebuffs any attempt to
cross it.

A nearby panel can be used to unlock the door, a level 5 Intellect task.

******* chamber 12
A rectangular chamber 90 feet across and 180 feet long.

This room is filled with shelves that are full of small square crystals. Most
are inactive, but the handful that are show either a slideshow of images, or
short films.

This seems to just be some kind of physical storage for photos and videos, long abandoned.

******** collapsed corridor 1
The multi-segmented body of a machine intelligence is crushed underneath the
collapsed ceiling of this corridor. At least, you think it's a machine
intelligence; it's a little hard to tell because of the damage.

It might be possible to dig a way through the rubble or the crushed robot, a
level 4 might task to clear enough rubble for someone small to slip through (
level 6 to clear enough for Zeno to get through )

If players succeed, they find the chamber connects to Chamber 16 through a
one-way phase door ( they can pass through into chamber 16, but not back through ).

****** chamber 16
A rectangular chamber that's 15 feet across and 30 feet long.

The far end of the chamber is an intricate fountain, with multiple height pools
and many spouts. However, instead of water it's filled with a strange yellow fluid.

There are some chests and boxes stacked along one of the long walls near the
door you used to enter the chamber. One of the boxes has been tipped over, and
you can what looks like shins and maybe a cypher in the detritus.

The cypher they saw is defunct, but if they search they can find:
 - A level 6 Nano Needler
 - 39 shins
 - A small flask of level 3 Numbing Oil
 - A small device, appears to be made of coral. Squeezing it causes it to
   extrude a key made of silver wires and hard light. This is the key for sealed
   exit A
***** sealed exit C
A force field blocks passage through this door. There is a panel next to the
door with 9 symbols you don't recognize. A level 5 intellect task disables the
force field, allowing you access to the chamber beyond.
******* chamber 9
A rectangular chamber, 15 feet across and 30 feet long.

The only things you can see in this room are some broken boxes, scattered scrap,
and some wide pillars at the far end.

******** hidden exit
The pillars actually are a clever illusion, hiding the edges of a false wall --
behind which is an exit from the chamber.

********* chamber 10
A hexagonal chamber barely 10 feet across

Contains nothing but a strange device that murmurs in unknown languages when you
approach.

There are no other exits from this room.
**** chamber at bottom of shaft (chamber 2)
A circular chamber with a 90 foot radius.

The ground is steelglass, beneath your feet you can see an incredibly complex
machine with thousands of moving parts. After staring for a moment you realize
that the machine doesn't return to a previous state, it's always moving to a new
formation you haven't seen before.

In the center of the chamber a portion of the device sticks through the floor --
a circle about 30 feet in diamter rises two feet from the floor. The edge of
plinth looks like its made from a weave of constantly shifting metalic
fibers. The surface of the plinth is a flat sparkling surface. Anything that
touches the surface will be drained of water ( inflicts 2 points of Speed damage
to a PC who touches the surface ).

There is a single exit, an accessway previously hidden by a panel of synth.

***** accessway
The only exit from the shaft, the accessway is cramped, and normal height humans
have to duck to get in.

The accessway winds back up the "outside" of the shaft a few times before
veering away, continuing for another 50 feet before opening up into a giant
cavity.

****** interstitial cavity 1
The accessway opens up onto a catwalk above a massive chamber roughly 900 feet
long and 550 wide.

About 15 feet wide, with no handrails or guards, the catwalk is suspended
several stories above the ground, and circles the perimeter of the room.

Within the chamber the air is hazy, caused by narrow vortices that move randomly
about the chamber. They drift randomly, sometimes combining or splitting apart.

A number of exits lead from the catwalk out of this chamber.

Growing from the ceiling is what appears to be a giant fungus colony. Upon
closer inspection you can see creatures climbing over the colony -- Colchin!

A group of six of them approach you on the catwalk.

In a series of grunts and hand motions, they seem to be trying to tell you not
to approach the colony. Either they're being extra cautious or they think you
can climb the synth walls as well as they can ( you can't ).

If the players nod or make positive noises, the colchin go back to where they
were standing and ignore the PCs. The PCs can ask questions to try and get
information, but the colchin only speak in grunts and hand gestures; they
apparently can't speak a language you know. If the players are antagonistic or
attempt to approach the colony the colchin on the catwalk will sound an alarm
and then attack. The alarm draws colchin from the colony, five to six more
appear every round.

[[file:~/Documents/CampaignNotes/Numenera-ThisOldShip/creature-stats.org::*Colchin][Colchin Stats]]

Group of five: horde, increase level by 2 and double damage.

******* trapped exit
This exit is blocked by a shimmering haze of sparkling energy.

Attempting to touch it or pass through causes 2 points of Speed damage and
prevents you from passing through.

You can see the emitter for the field on the other side of the shimmering haze
of energy, it looks like something cobbled together from random numenera and
junk laying around.

There is a panel affixed to the side of the doorway, it probably controls the
field. A level 5 Intellect task will disable the field of energy.

On a failure the area around the door is filled with a shocking energy that does
8 points of damage, anything within close range of the door is
effected. Touching or attempting to pass through the field of energy causes 2
points of Speed damage.

******** chamber 6
A hexagonal chamber 30 feet across. The ceiling of the chamber is a mess of
pipes and cables.

Despite the temperature being the same as everywhere else in the ruin, water
leaking from these pipes has frozen into what you first think are stalactites
and stalagmites. However, upon closer inspection you see that they're not either
of those, but are _statues_. Each seems to form the likeness of a person. There
are unfinished statues, the ice not having built up enough mass to be a whole
person.

One of the statues is wearing your shoes.

A single exit is found opposite the door you entered from.

********* chamber 7
You've found the hideout of Ghoka's gang. 

You're in a rectangular room, 30 feet across and 60 feet long. The door you
entered the room from is on one of the short walls.

Halfway down the room are two large, hovering, spinning metallic spheres.

The spheres seem to be malfunctioning. A sphere might drop a few feet before
stopping and then floating back to their original position. Maybe it will
suddenly stop spinning, spin in the opposite direction for a moment before
immediately changing direction. One seems to be rotating around an axis set on
the horizontal plane, though the axis switches angles quickly; shuffling through
a random number of angles before snapping back to the horizontal. They also
flash red occasionally. Despite all this activity, the spheres are completely silent.

There are no other exits that you can see from this chamber.

Between you and the spheres are a number of boxes, cots, and scattered
trash. The boxes appear to be part storage, part wall or dividers; they're being
used to demarcate areas. None of the "walls" is more than a foot or two high for
the most part.

On the other side of the spheres is a more open area, with some of the panels in
the floor having been pried up to reveal a pit of some kind. From where you are,
you can see some of the gang members clustered around a man on the edge of the
pit. From what you can see he's a wall dressed man, with dark skin and brunette
hair cut in a faux-hawk.

The well-dressed man seems to be arguing his case, but the gang isn't buying
whatever he's saying. After a moment the biggest gang member steps forward, and
says something to the well dressed man. They both laugh for a moment, then
without warning the big gang member pushes the man into the pit. You hear the
sound of a squad of table saws and drills being activated along with the screams
of the well dressed man.

The screams are suddenly cut short as the whine of the drills and saws takes on
a... wetter tone.

=======

The pit is about 20 feet across, and contains a xacorocax.

Ukrurg will challenge the party to a fight. If they refuse or run he'll
attack. He should come across as a bit unhinged (kinda Kharn-ish).

Ghoka is currently not in the ruin, currently home are the following:

- Ukrurg Sovil, second-in-command ( [[file:~/Documents/CampaignNotes/Numenera-ThisOldShip/Maka_Tho/immaculates.md::They're not good people.][but not really]] )
  Uses "Deadly Warrior" stats ( bestiary, pg 140 ):
  Level:  6 (18)  Health: 28 [28]  Armor: 3

  Modifications: Attacks and might defense as level 7, speed defense as level 8 (
                 partially due to shield )

  Combat:
    Can make single attack with weapon for 10 points of damage, but can also
    attack two different foes as single action, doing 8 points of damage with each
    attack. All their attacks ignore armor.

  Carries:
  - 52 shins
  - Stasis detonation grenade, level 10
  - Vocal translator, level 3
  - An oblong metal plate covered with strange inscriptions and diagrams

- Fifteen bandits, split into three groups of five:

  Bandit grouping:
  Level: 4 (12)  Health: 30  Armor: 2  Damage: 8 points

  Modifications: speed defense as level 5 due to the shields they carry

  Combat: Armed with axes and swords and simple shields. If Ukrurg Sovil dies
          and more than half the bandits are dead, the rest will give up.
  
  Loot:
  - 55 shins
  - Banishing Nodule, level 5
******* chamber 5
A circular chamber with a radius of 15 feet.

Standing in the center of the chamber is what appears to be a pillar made of a
metal with a strange shimmer to it, covered in a design that looks like ribbons
etched into metal.

Any object or creature that gets within five feet of the pillar causes it to
activate: a ribbon of molecule thin material unwinds from the pillar and then
makes a level 6 attack against the object or creature. Objects are destroyed,
creatures move down one step on the damage track.

There are no other exits from this chamber.
******* blocked exit
This doorway is covered in a strange fleshy mass. If touched it does 1 point of
Speed damage. The door can be opened, but the entire corridor beyond is full of
the strange fleshy substance -- including strange glowing blisters and some very
deadly looking spines.

Attempting to enter the corridor results in an attack from one of the tendrils,
which is a Level 9 defense task and moves the PC one step down the damage track.
******* blocked exit
There is no door or gate in this doorway, just what looks like a very detailed
painting or photo of some kind. 
******* blocked corridor
This doorway opens into a corridor that travels straight for about 20 feet
before curving down. Shortly after it begins to curve it ends abruptly in a pile
of rubble, the ceiling collapsed at some point.
******* chamber 4
A rectangular chamber, 30 feet across and 60 feet long.

The long walls are a deep but bright blue. Painted on these walls every 6.5 feet
is a white circle about 2 feet across with the outline of a hand that is not
human etched into the synth wall within the circle.

Above each circle is a pipe that ends in some kind of feeding apparatus. It looks
like it might fit on your head.

If they touch one of the circles, some sort of white paste is pumped out of the
tube. It's harmless, slightly nutritious, but tastes _terrible_

There are no other exits from this chamber.
***** chamber 3
A twisting corridor 30 feet long with what looks like framed paintings hung on
either side. The paintings seem to be random splashes of colour, but they change
each time you look at them.

A square chamber, 50ft to a side.

Contains thin glass panels floating in the air. Each is barely thicker than a
sheet of paper, and edged in gold trim with swirling flourishes that seem to
symbolize water or a flow. The glass panels are slightly tinted, giving them a
mirrored effect on their surface.

Looking into a panel you see the strangest sight. From the moment your eyes
look into a panel, your reflection starts moving in reverse -- backwards through
time. Not only that, but each one seems to show a slightly different reality. In
some you're alone, others you are with a party of explorers. However, it's not
always the same party standing with you in the chamber now.

There are no other exits from this chamber.

Intrusion: A shadowy reflection leaps through the glass pane, shattering it -- and
bringing the shadow into the chamber with you. The reflection stands before you,
mirroring your movements. You notice that it has some very wicked looking
claws. When you try to move away it follows, coming a bit closer with every
step. 
