:PROPERTIES:
:ID:       7f8b06da-122a-4cd3-885f-205d9ab8b7b0
:END:

* Inbox
** Character Songs To Listen To
*** Zeno
Scene:
Confrontation with the Merchant/ Encounter with the Merchant:

(I couldn't not use this song for Zeno its too perfect)
https://open.spotify.com/track/4Oih3RDrSFg3afaOphBVuy?si=941ac618836f4187
or
https://open.spotify.com/track/7EPbzLbSzg9d94LZ9MnKFA?si=41fff19d535544ed


and finally if I made a Zeno MV:
https://open.spotify.com/track/5D29PI3g8UmTHLnjX7e3CQ?si=dff2a30809774535

 - the merchant is the one that modified Zeno

*** Ureos
*** Klep
*** Ureos
[11:57 AM] Nethew: I think I thought of a cool moment that Ureos could have at
some point. I'll have to think of some lore behind it, but I love the idea that
his people have a forbidden "dance of death" that basically channels the latest
energy/ether in your surroundings through you to hyper-empower yourself and your
allies, but at a great physical cost. Would be cool to have a moment where we're
just up against crazy odds and he has to bust this out as a last resort.

Mechanically I'm thinking it's something where I'd have to burn an intrusion,
and have a heavy effort cost that increases per turn, so it'd be super dangerous
and potentially lethal. Probably have some permanent lasting effect on Ureos too
if he survives.

Had this idea while farming a FFXIV instance last night. The music for it was
super hype and I felt like it'd fit that kind of moment really well
https://open.spotify.com/track/3FSTlftDW03EvQOBzyroIP?si=a836adad675f4008

[12:05 PM] Nethew: Actually, I just thought of a great lasting effect it could
have. It could change his descriptor entirely so he isn't graceful any
more. Maybe to something like Clever, Cheerful or Nurturing.

[12:24 PM] Nethew: Also, I was talking about character conflicts with Don and
Will and they were asking what would happen if Ureos's family was in trouble
back in the Steadfast and I was like, "He'd probably go back, no
question". Which made me wonder, is the portal between Ararholm and the
Steadfast still open?

Ureos' family is alive and well, but if family drama comes up later on in the
campaign when the world is at stake it might make for some good Family vs. Found
Family stuff.

[2:11 PM] Hagen: portal is still open but it's like a 2-month trek just to get
to the portal ( plus more walking on the other side ) -- although, a ship would
drastically reduce how much time it takes 😄

[2:11 PM] Nethew: Ooooo

[2:11 PM] Nethew: Good to know!

[4:36 PM] Nethew: Heard this today as well and immediately thought that it would
fit so well if we ever had to fight a big bad from the Sable Hedgemony
https://open.spotify.com/track/3zmG5m9riAuH0igUmqLrBH?si=89dcb37217ea48c8

*** Fox
Okay, I think the song I’m going to go with is Party Poison by My Chemical Romance.

https://youtu.be/iw_-pACvP-A
YouTube
My Chemical Romance - Topic
Party Poison

[7:26 AM] Jessy (DMs of Vancouver): I’m thinking kind of a scene where Fox
initially has to face a big threat (maybe a large group of bandits or some sort
of swarm/mob) alone and kind of one by one NPCs and party members enter the
fray. Kind of culminating in a big fight in town with everyone getting involved.
