* This Old Ship
** Style
Ideas on how to run the game, the style, the tone, etc.

- play the really bad guys completely straight -- they should be the completely
  "straight man" to the wackiness of the party 
- less bad ( but still bad ) can be flamboyant, etc, but still be "obviously" evil!
** Travel
# Travel Speeds
- what's marked on the hex sheets is for travel on well maintained trade routes
- the only trade route is the one already marked on the handout map

# Distances 
- 112 hours (4 days, with good weather) on road from Ararholm to City of the Dead 
- About a day from City of the Dead due west to Lost Caravan
- 12 hours south on the road from City of the Dead is the Caravan Attack Site
  for scenario 7

# Getting Lost

# Encounters 

# INTRUSIONS
** Salvaging
[take notes on page 107 on for salvaging]
** Maybe A Terrible Idea
Okay. So. The bad guys.

Deceit
Doubt
Hate
Vanity
Despair
Scorn
Anxiety
Absurdity

A lot of those might work really, really, *really* well if they're
shapeshifters. Or psychic. Or able to pull them into alternate dimensions,
pocket dimensions, stable time loops, or whatever it takes to get each of their
targets alone for just a moment so they can try to defang a potential threat.

Each will try to tempt a PC, potentially teaming up.

| Demon     | PC    |
|-----------+-------|
| Deceit    | Fox   |
| Doubt     | Belel |
| Hate      |       |
| Vanity    | Klep  |
| Despair   | Belel |
| Scorn     | Fox   |
| Anxiety   | Zeno  |
| Absurdity | Ureos |

Offer each player two different versions: the 2xp version, and the 4xp version.

*** 2 XP Versions

*** 4 XP Versions
Vanity disguising itself as Mex, and tempting Klep into further modification --
"the others aren't smart enough to understand the kind of vison it takes to
change yourself like this, right Klep?"

Anxiety disguising itself as Mex or Pamki to plant ideas in Zenos head that he's
maybe not a person, not a human, just a sad robot.

The story of the brain in a jar that thinks its a person but has really gone
insane. Get permission from the table before dropping this heavy bomb on
them. Lay out that this isn't the NPC they think it is, it's one of the bad
guys, Anxiety -- in disguise, deliberately trying to fuck with Zeno so that he
won't be as effective an ally. Make sure they understand that this is the
literal embodiment of the concept of Anxiety if it were crafted by the Devil
Himself.

Doubt & Despair disguising themselves as
 - the person in the party Belel trusts the most
 - the NPC Belel trusts the most

They come to Belel and lie about how everyone feels about them. They think that
having Belel around was great, but whatever this /new/ thing is with the dome is
just too much. One doesn't think the residents will ever feel safe while Belel
sticks around. Etc, etc. Write out a *short* little monologue from each that's
meant to be one of those "the literal meaning of what you said is nice but the
intent and unspoken meaning is real, real mean" kinda things.

Scorn disguised as the Sheriff, and Deceit as Pamki. Scorn basically plays it as
Fox finally crossing some line and threatening to tell Pamki about what really
happened when Fox rescued Pamki. Deceit "unfortunately heard every word from
just outside and couldn't take it any more and just had to come in and say
something and that is that she can't believe Fox would turn out to be just like
all the rest, nothing more than a rutheless killer".

Absurdity goes for Ureos. Gets him drunk, or high, or both, or something
else. Puts him in a suggestive state of mind, more ameniable to the likes of a
guy like him pouring him a suggestion or two, right? It's pretty wild that folks
'round these parts have put up with him for so long, hey? Usually by now folks
would have gotten tired of you. Either some town getting that look in their eye
like they're about to start accusing you of stealing babies, or kisses, or both!
Ha, that story was funny, you should tell it again some time. I don't know
what'd be worse, that, or just having your family walk off without you one
day. Yeah, I know you said what you said but man I thought the same thing until
I ran into my brother once. This was before I came here, but before I joined up
with Ager I was once in a huge family, right? I thought we were super close, but
then they told me I had to go to school and grow up. I found out a few years
later from my brother when we got drunk together that my parents just told me
that to get me out of the house so they could have some time to
themselves. Messed up, right, what a parent will say to their kid when they're
too lazy to be a parent?

*** Heal Some Broken Hearts
IMMEDIATELY AFTER each scene, give the player as long as they need, and then
have them choose who their character runs into next.

They can choose another PC, or one of the NPCs.

In either case, the player also gets to choose who voice the NPC. I will give a
small amount of guidance, but otherwise the NPC will be completely in the hands
of that player.
