* This Old Ship
** Travel Roles
*** Klep - navigator
person in charge of path-finding through the wilds
*** Zeno - scout
can travel ahead to check for hazards and whatnot
*** Belel - cartographer
required if needing to come back easily, or to tell other people exactly where a
ruin is
*** Ureos - rear guard
the person who's responsible for making sure nothing sneaks up on the party as
they travel
*** Fox - general guard
the person who's responsible for making sure that nothing ambushes the party
from in front or above
** Style
Ideas on how to run the game, the style, the tone, etc.

- play the really bad guys completely straight -- they should be the completely
  "straight man" to the wackiness of the party 
- less bad ( but still bad ) can be flamboyant, etc, but still be "obviously" evil!
** Travel
# Travel Speeds
- what's marked on the hex sheets is for travel on well maintained trade routes
- the only trade route is the one already marked on the handout map

# Distances 
- 112 hours (4 days, with good weather) on road from Ararholm to City of the Dead 
- About a day from City of the Dead due west to Lost Caravan
- 12 hours south on the road from City of the Dead is the Caravan Attack Site
  for scenario 7

# Getting Lost

# Encounters 

# INTRUSIONS
*** Players
 - Need to tell me /how/ they're travelling -- quickly, normal pace, carefully,
   etc.
** Salvaging
[take notes on page 107 on for salvaging]

* Summary/Outline
These are long-term plot threads, until they come into the foreground they
should be kept as hints and bits of lore in the background (mostly).

There are three main types of quests or adventures for the party:

1. Saftey & Security
2. Resources
3. Exploration

Any quest handed out should touch on one of those areas.    
** Safety & Security
These are quests that help make Ararholm safer. Some may involve chasing off a
monster or a demon or two. Others might require finding a way to deal with a
gang of bandits. As the town grows, it should improve its defenses -- and there
are many ways to make a village secure in the Ninth World.
** Resources
The village is slowly running out of resources. In the case of water, they've
reached the limit of what they're easily able to access. In addition to securing
good sources of food & water, there are materials to consider as well. Stone,
wood, and synth are needed for building new structures. Iotum and other
resources are needed by the wright to do their job.
** Exploration
While Ararholm sits on top of a mesa with a good view of the surrounding area,
they don't really know what's out there in the region. 

Maps need to be made, dangers need to be found and dealt with, travel routes
need to be established. Ararholm is potentially only the first settlement in the
area, if there are other places that could be made safe and settled then
Ararholm's chances of survival go up.
* Plot Ideas
** In Ararholm
*** Deal with Ghota
Drivers: Pamki & Sheriff
*** Fix Machine in Ship or Find New Water Source
Drivers: Pamki
*** Improve Defenses
Drivers: Sheriff, Mex
*** Find Reliable Sources of Resources
Drivers: Mex, Mason, Woodworker

- mex needs materials (synth, iotum) to build devices to help the town
- the mason needs a new quarry soon, the one he's used until now shouldn't be
  expanded much more (otherwise it'll destabalise the mesa), he'd like someone
  to scout out some of the nearby forests to see if they're safe and have wood
  that can be used
- woodworker needs a decent forest for wood, most of the nearby sources of wood
  have been exhausted
*** Scout Ruins
Drivers: Mex

mex has information on a number of ruins nearby, 
*** Information, the Ship
Drivers: Aeon Priest

while he has a couple of projects on the go, the aeon priests main concern at
the moment is split between two locations: 

- the weird ruin near his home/enclave
- the ship

he wants to make sure the ruin is safe, and then to pick it clean of secrets,
numenera, and information

he is intensely curious about the ship, but doesn't want to step on pamki's toes
** Nearby
*** Ghoka's hideouts
Drivers: Sheriff

Ghoka is a problem that needs to be solved, but first you have to track him
down.

The sheriff would also like to make sure there isn't something hiding in one of
those ruins that could pose a problem for Ararholm
*** Diplomat's Arrival
Drivers: Sheriff, Pamki

apparently the Sable Hegemony wants to send a diplomat, to talk about the terms
of the contract that granted Ager the right to found a town

once they arrive:
- willing to pay for information about land that would make good land for
  farming (Calda needs somewhere it can use to replace the farmland lost in the
  Undying War)
- a very big bounty is posted for any information about the Voz Dynasty
  - if they've been spotted, where and when and how many 
  - if someone is willing to scout out where they might be entering into
    Maka-Tho, that person or persons would get a title for sure
    
*** Mapping The Region
Drivers: Pamki

Pamki wants better knowledge of the area -- she needs maps! 
** Regional
*** Rumors [0/2]
- [ ] word has reached town that there's a forest of giant mushrooms to the west
- [ ] word has reached town that there's a forest of giant red trees to the west south-west
** Calda
** Sable Hegemony
*** The Army Comes to Town
Eventually the Sable Empress sends a company of the army to Ararholm.

Sent to the region by the Queen as a way to say "you're part of the Hegemony, don't forget it" 

this causes issues in town trying to impose their own rule & order on the place
*** Pathfinding
The Royal Throne will pay handsomely for information on any routes leading
through the Kashin Baya mountain range into Calda

** Voz Dynasty
currently busy with their own invaders for the most part

they are expanding into the northern regions of Maka-Tho
** Folks Yet To Show Up
** Finale
[[https://www.pinterest.ca/pin/724446290064809769/][This is what the party needs to rebuild]] to stop the Nightmares -- because
they're actually heralds of something **much** worse.
