Just a place to keep stats for easy reference.

* Colchin - 4 (12)
Motive: Defense
Health: 12  Damage: 5 points  Armor: 2
Movement: Short
Modifications: Knowledge of fungi as level 7

Combat:
  Colchin prepared to fight wear fungal layers that provide 2 (or more) points
  of Armor and have one or more strange weapons at hand, including a spine
  thrower. A colchin with a spine thrower can make a short-range attack that inflicts 5
  points of damage, and on a failed Might defense task, inflicts 1 additional
  point of Speed damage. Some colchin also carry a spore bomb, which acts like a
  level 6 corrosive spawn detonation but does not count against a character’s
  cypher limit.


Interaction:
  Colchin speak their own language but can make themselves understood using
  gestures and hand motions. They are open to negotiation, as long as no
  cultural taboos come into play. For the most part, they are opposed to
  allowing non-colchin to enter their communities.
  
Use:
  A colchin hunting party has gotten into trouble with local human villagers,
  each claiming the other as the antagonist. The PCs are called on to help both
  sides.
  
Loot:
  A spine thrower (depletion: 1 in 1d10) or spore bomb might be found in a
  colchin’s belongings.
  
* Ruin Defense Drone - 4 (12)
Motive: capture intruders
Health: 12   Damage: 2   Armor: 3
Movement: Short, flying
Modifications: defense as level 7 ( small )

Combat:
  The defense drone uses a small paralysis ray to attack. On a successful hit it
  does 2 points of speed damage, and the target must make a Might defense
  roll. If they fail, they are knocked unconcious -- at which point the drone
  will use a gravity field emitter to pick up the creature and take it to
  "jail".

  If attacking as a horde, all drones will target the same creature with their
  beams. If struck, the creature will still only take 2 points of Speed damage,
  but the difficulty of the save roll is increased to 6.

Loot:
  D6
  1-2 the paralysis ray can be scrounged for a Ray Emitter (paralysis)
  3-4 the gravity field emitter can be salvaged for a Gravity Dampener
  4-6 the gravity field emitter can be salvaged for a Gravity Nodule

* Yellow Swarm 5 (15)
Motive: Hugners for various organic compounds
Health: 18  Damage: 5  Armor: none
Movement: Short, flying
Modifications: Speed defense as level 6

They look like a small cloud of yellow locusts until you get close enough to see
that they are transparent and oddly configured, with asymmetrical bodies that
have seven legs and five wings.

Combat:
  A yellow swarm moves in and attacks with hundreds of tiny bites and stings. The
  trick of fighting a swarm is that it fades in and out of reality, so every
  round, the GM rolls a [1d6]. If the result is 1-3, no attacks or special
  abilities will affect the swarm in that round, but the players don't learn this
  until after they have declared their actions. However, the swarm always attacks
  just before or after fading, so it is always able to affect creatures in this
  world.
  
  Tell the players that due to the strange effect these creatures have on
  reality, combat will work a bit differently. Players will make describe what
  actions they wish to take in initiative order, and the GM will describe how
  the round plays out after they've all described what they're going to
  do. After they've all gone, tell them the result of the roll, and then the
  creature will attack.

Interaction:
  It's not possible to communicate with the swarm.

* Vex Goblin 4 (12)
Motive: Build & protect Vex structures
Health: 12 Damage: 3 Armor: 1
Movement: Short, or teleport
Modifications: Temporal manipulation at level 6

A humanoid automaton that moves in smooth yet still somehow jerky movements. Its
head dominated by the semi-circular "crown" or frill, tapering down to a point
before its single red sensor eye.

Set into its abdomen is a glass canister full of a glowing milky-white liquid.

All come equipped with a strange rifle that fires not bolts of energy, but what
seems to be a circuit pattern made from red light that moves with great speed.

Combat:
  Will advance towards enemies until it is a just under a long distance away, at
  which point it will open fire.

  If damaged enough it may literally lose its head, at which point it will
  teleport into immediate distance and begin attacking with melee attacks.

  Attacks targeted at the glass canister bypass armor but are hindered by one
  step.

Interaction:
  If inactive, Goblins will do nothing unless disturbed (either directly, or by
  messing with something they were set to protect).

  If active but engaged with a task will ignore creatures (again, unless they
  disturb the Goblin directly or they get too close or mess with what they're
  guarding/building/etc)

  If a single Goblin decides that combat is necessary, it will send a command
  signal causing all nearby Goblins to enter combat mode.


