* Numenera
** Cyphers
** Artifacts
*** Sword Arm Mods, Level 4
Two mods, one for each arm.

Can be implanted within mechanical arms to provide the following benefits:

   As an action, can fire 5 splinters at any creature within short range to
   inflict 5 points of damage that bypasses armor.

   By spending Might effort another 5 splinters can be fired for an additional 5
   points of damage ( also bypassing armor ). You can expend effort to increase
   the number of splinters up to a maximum of 30 splinters doing 30 points of
   damage. All splinters are fired as a single action, but each target requires
   it's own attack roll.

   Once fired, splinters must be retrieved by touching the body or central mass
   of where the splinters hit. Unrecoverable splinters regenerate at a rate of
   5/day.
   
**** Notes
Mex will have mentioned to Zeno that she thinks there may be alternate weapon
forms that can be unlocked, the sword was apparently one of a larger "set" of
weapons. Each weapon had a control crystal of some kind, Mex simply unlocked a
little bit more of what the sword could do.

*** Jeweled Dancer's Bracers, Level 4
A set of bracers, artfully carved with scenes of dancers & musicians. Set into
the bracers are a number precious metals, with bits of wire, shiny metal
baubles, & fragments of glass or crystals. As the user moves their arms, the
bracers catch and reflect light in strange ways. The hanging bits can produce a
rhythmic, almost drum-like sound if the user is skilled enough.

These shiny bits can be used to great effect by someone dexterous & skilled
enough. Meant to be worn by skilled dancers or storytellers as an aid to their
craft. The various bits

Can be activated ( requires an action ) to produce one of the following actions:
 - attempt to stun all other creatures within immediate range with lights & sounds
 - attempt to inspire one allied creature for the next turn, easing all tasks by
   one step

By spending a level of effort, you can choose one of the following additional
effects:
 - the range of the effect can be increased to short range
 - the difficulty of the check to stun or inspire is decreased by one step

By spending two levels of effort, you can get both additional effects.

**** Notes
Mex lets Ureos know that she thinks that some of the original pieces were lost
over the years and replaced with inferior components. There may be pieces of
lost technology she can use to improve the bracers; anything that deals with
resonance or acoustics may have bits she can use to improve the bracers.
*** Black Leather Bracers, Level 4
A single bracer meant to be worn on the dominant arm.

Can be activated ( requires an action ) to produce a buckler shield of smoke and
darkness. This shield harnesses Belel's innate gifts, and so won't work for
anyone else.

The shadow buckler shield provides 1 points of armor, and eases Speed defense
tasks by one.

By expending a point of effort, you can increase the size of the shield from the
size of a buckler shield to that of a kite shield, providing an additional point
of armor.

If you expend a further level of effort the shield becomes a wall of darkness
with a surface area no greater than 50 square feet -- so a wall 10 feet wide and
5 feet high ( or 5 feet wide and 10 feet high ) or anything you can imagine so
long as it's no bigger than 50 sq ft.

The fully expanded shield hinders any attempts to perceive what is on the other
side ( regardless of what side you're on ). Attempting to pass through the
shield wall produces a cold and empty feeling. The user of the bracer can choose
to require an Intellect check for those attempting to pass through, on a failure
they take 2 points of Intellect damage and fail to pass through the wall.

The shield is attached to the bracer and can only be powered by
Belel. Basically, if Belel moves the shield moves.

**** Notes
Mex tells Belel that she thinks that with the right pieces of tech she should be
able to make it so the bracer can keep the shield "real" while being detached
from the bracer, potentially allowing Belel to place the shield as a barricade,
or use the buckler form as a ranged weapon.

*** Probabilistic Crystal Shield, Level 4
A buckler shield seemingly made from a mostly clear crystal with milky strands
of a strange mineral running through the crystal. When worn, looking through the
crystal provides glimpses into possible futures.

Provides 1 points of armor while worn, and eases Speed defense tasks by one step.

Can be activated to produce one of the following effects, once per day:

 - Create a flash of light that gifts a confusing sense of foresight to a
   creature you choose within short range. All of that creatures attacks are
   hindered, while all attacks against them are eased for two rounds as they try
   to figure out which hazy image is their real attacker.
 - Create a flash of light that gifts a gentle sense of foresight to a creature
   you choose within short range. All of that creatures attacks are eased, while
   all attacks against them are hindered for two rounds as the shield grants
   them the ability to see a moment into the most likely future.
 - Cause the shield to shine brightly on an object or creature, allowing you to
   divine one thing about its future. You may ask a single yes-or-no question of
   the GM who must answer truthfully; but it must be about something that
   happens to that you could feasibly see from where you current stand. For
   example, you can ask if a candle will get lit -- but you'll only know the
   answer if the candle is lit before it's moved.
**** Notes
Mex tells Klep that she thinks there may be other crystals ( or whatever they
actually are ) out there she could incorporate into the armor. She does mention
that the crystals have something to do with the Vex, which she doesn't know much
about.

*** Stone Bracers, Level 4
A pair of bracers that ease all melee defense tasks by 1 step.

Can be activated ( requires an action ) to provide the following benefits:

 - Your arms from finger tips to mid-biceps turns into a stone-like
   substance. It doesn't hinder your movement or dexterity at all, however it
   does give you an additional 1 armor against melee attacks.
 - While you have stone arms, your grip strength is increased dramatically,
   easing any tasks requiring grip strength ( climbing, disarming opponents, etc
   ) is eased by one
 - You can spend a level of effort to increase the density of your arms, which
   gives you 2 points of armor piercing for unarmed attacks

However, for each hour that your arms are in stone form you lose a point of
Might as the gauntlets work to try and prevent the stone form of your arms from
becoming actual stone.
**** Notes
Mex tells Fox that with the right data & samples she might be able to tune the
gauntlets to provide one of the following benefits:

 - change the type of stone ( may add a damage bonus, or other features )
 - reduce or eliminate the health drain
