* First Protector
:PROPERTIES:
:ID:       79aea72e-b0e2-4f6d-a0e0-c950ca168e64
:END:
Back before Sudboia was Sudboia, there were the clans. There had always been the
clans, and the clans would always be.

The clans did as clans do: they traveled, protected their territory, and traded,
fought, and partied with other clans.

One day, a single member of the Khan Clan presented himself before two hunters
of the Oda Clan. The Khan Clan and the Oda Clan had been antagonistic towards
each other for the last few generations. Things hadn't erupted into outright
fighting, but small skirmishes over resources were somewhat common. 

The Oda Clan hunters almost killed the Khan Clan member immediately, but two
things caused the hunters to lower their spears and put away their bows.

The first was the position of absolute humility that the Khan Clan member had
used to present himself: on his knees, hands on his thighs, palms out. This
position had many names, but one purpose: to present oneself as lesser or
subservient. No weapon to hand, and in a terrible position to be in should the
person they are talking to decide to attack. Such a position of deference was
reserved for one of two occasions: when surrendering to another clan after a
battle in order to save what lives remained -- or when a messenger wanted to
ensure that their message was heard, by presenting themselves in a way that says
"you can kill me, just let me speak, first"

The other reason the Oda Clan didn't attack was, well, everything else about the
Khan Clan member.

For so long, the Khan Clan had been mocked as wanting to rule. The joke was that
their name should have been the Khon Clan -- the "King" or "Ruler" Clan. They
dressed in fancy silks, wore gaudy jewlery, and their weapons were often so
gilded and covered in ornamentation it was a wonder they still worked as
weapons. But despite how they looked, the Khan Clan had the skills to back up
their ambitions. They had only been stopped when several other clans banded
together to force the Khan Clan to stop their expansion and atone to the clans
they had attacked.

This member of the Khan Clan none of those things. Barely alive, they collapsed
in front of the Oda Clan members, passing out from exhaustion. The two Oda Clan
members quickly decided getting this person help was more important, feud or
no. That decision saved the lives of every Sudboian who survived the war up
until the present day.

The two Oda Clan members managed to get the Khan Clan member back to their
halting site quickly enough to get him some medical attention. However, his
wounds were too severe; a combination of weapon blows and spending weeks
traveling by foot had done some serious damage.

Before he died, the Khan Clan member passed along a message. He spoke to the two
hunters who had found him, a handful of the Women's Circle, and the clan chief.

"I am Khan Gi Ko Runk. I am the last of the Khan Clan. They are coming for every
clan, and none of you have the might of sword or strength of bow to turn them
back. Please, take this and warn the other clans. Make them believe you -- or
our ancestors will never reach Valhom, and all our names will be naught but dust
and ash."

In his hands, held so tightly it had dug and cut into his flesh, Khan Gi Ko Runk
held the Sword of Jade -- the artifact said to be the source of the Khan Clan's
might and wealth. The location had been a closely guarded secret for hundreds of
years; for a member of the Khan Clan to not only willingly hand it over, but to
hand it over as proof the Khan Clan was dead and gone was all the clan chief of
the Oda Clan needed. The Women's Circle agreed that no member of the Khan Clan
would willingly surrender the Sword of Jade unless nobody else was left alive.

By the time they finished discussing the sword and what to do about the message,
Khan Gi Ko Runk had died.

Every member present swore an oath that very moment.

The Oda Clan chief declared that he would not rest until whoever was responsible
was dead. The Women's Circle said they would send messengers to all the clans:
meet on the Ikara Plains. The two hunters vowed to not rest until every clan
heard the message and agreed to meet on the Ikara Plains.

A stretch of grassland nearly completely empty but for the gently billowing
stalks of ikagrass, the Ikara Plains had been used as a neutral meeting ground
for centuries.

The only thing that stood there at the time was the pillar and the gate.

To be considered "at" Ikara Plains, one had to travel through the gate from
south to north. This was considered to be the same as making a pledge of
non-violence, similar to what a visiting family or clan might do when meeting
another clan. Breaking such a pledge was considered to be the same as
purposefully defacing and then burning a families Kohk Chi. 

The only other structure at the meeting grounds was the pillar. The pillar was
column of smooth rock that stood ten feet tall. Anyone who wished to speak to
the those gathered at the Ikara Plains would get up on top of the pillar. When
they spoke, everyone who could see the speaker would hear them as if they were
standing next to them.

As each clan arrived, they all saw the same thing. The leader of the Oda Women's
Council, a gruff old woman harder than stone known as "Grandma Oda". She stood
upon the pillar, the Sword of Jade held in her hands, tip touching the
pillar. All of the rest of the Oda knelt around the pillar, facing
outwards. They had assumed the position of deference, hoping that would be the
first arrow in their quiver as they attempted to convince the other clans.

As more and more clans arrived, they began to clamor for information. They
shouted and jeered, some even going so far as to imply the Oda Clan wished to
brag about defeating the Khan Clan with as little grace or honor as possible. 

Despite this and worse, the Oda Clan stayed put. Grandma Oda stood on top of the
pillar for a week. Somehow, without food or water, Grandma Oda stood on the
pillar and stared down any who dared to challenge her or her clan's honor. That
icy stare quieted most hecklers after a while.

Eventually, all the clans had arrived. When the last member of the last clan
passed through the gate, Grandma Oda spoke.

"Be. Quiet."

Those two words silenced every mouth on the plains. Even those not looking fell
quiet as they turned to look at Grandma Oda. In some cases, people were so far
away that Grandma Oda was barely a speck on the horizon. But thanks to the
pillar, everyone heard her.

"We did not bring you here to gloat. We are not here as conquerors. We are here
as witness, and as avengers.

Two weeks ago, a member of the Khan Clan showed up on our lands, before two of
our hunters. He prostrated himself in the manner we all do before you now,
hoping the hunters would choose to hear his message. He was brought back to our
halting site, where I, Oda Ken Chief, several members of the Women's Council,
and the two hunters heard the messengers words. I committed them to memory, and
have been repeating those words to myself since.

I did so because I wanted to understand his message fully before passing it on
to you. I needed to know what might lay behind his message. If it was a trick or
some kind of subterfuge. It was neither of those things. It was, and still is,
the most powerful thing any of us have: the truth.

So listen to his message, as I have heard and remembered, so that you can
remember and pass it on yourselves."

Grandma Oda paused for a moment, taking a moment to look at all those gathered
around her. What she was looking for nobody is sure, but apparently she found
it, and was satisfied.

When next she spoke, she used the truth voice; a way of tone and timber taught
to high ranking members of the Women's Council. The truth voice is special, and
only used in very specific occasions: when the speaker knows, without a doubt,
that what they are saying is true.

"I am Khan Gi Ko Runk. I am the last of the Khan Clan. They are coming for every
clan, and none of you have the might of sword or strength of bow to turn them
back. Please, take this and warn the other clans. Make them believe you -- or
our ancestors will never reach Valhom, and all our names will be naught but dust
and ash."

After she finished, she looked out at the gathered crowds. At the faces showing
so many different emotions. A few voices started to cry out, questions lost to
the wind.

Grandma Oda spoke again.

"Be. Quiet."

She lifted the sword, and tapped it once against the stone column. A tiny sound
that echoed across the plain like thunder.

"We did not abandon our lands to bring you lies. We did not send our quickest
and best hunters racing across the plains to gather you up to deceive you. We
did not wait here, fasting, committing the words of Khan Gi Ko Runk to heart,
etching them into our souls.

He did not brave the plains alone, for ancestors know how many weeks, to hand
over the greatest treasure of the Khan Clan to one of their most hated
rivals. He did not save his last breath for this message, only for it to wither
in your ears!

We did not send our bravest and best warriors into the lands of the Khan because
we thought the gods had struck our enemies down. We did not send them out after
performing the ancient Oda rights of passage because we thought there was no
danger to be found from the Khan.

We sent them out under a flag of war, to bring vengance for the Khan.

We sent them out as dead women and men, walking ghola, because we were certain
they were heading into doom.

We sent them out, hoping they would bring word back that the Khan had been
felled by disease, or famine, or some accident or play of the Gods.

We sent them out dead, and hoped they'd return.

We sent them out over a week ago, before any of you arrived.

We sent them north, from here, on what should be a two day ride to reach the
heart of the Khan homelands."

She stopped, and slowly turned once more to look at all those gathered.

Before speaking, she tapped the sword on the pillar once more, sending out
another ringing peal of thunder.

"We are here, now, to tell you our warriors are dead.

We are here, now, to tell you that something terrible lay over that horizon.

We are here, now, to ask -- no, to beg.

We, the Oda, killers of the Silvered Flags, wielders of the Steelglass Bow, sons
and daughters of the dire wolves of the plains, walkers of the 6-fold path -- we
are here to beg you, all of you: it is time to march. Whatever is waiting to the
north, whatever killed the Oda, and our warriors, we need to face it now, with
the full weight of all our swords and mounts and spears and warriors. Together,
as a single blow, we will tell whoever this invader is that while we are all
clans apart, separate and divided, we are also a clan of clans, a family that
has walked every inch of this plain and knows it as our own.

We beg you, humbly.

I, Oda Kina Uma Shire, beg you.

No, wait. You all need to understand what we have come to understand.

As we have waited for you all to arrive, we have discussed how to convince you
of why this is necessary. How to convince you this isn't retribution against the
Khan, or a trick of some kind or another.

For you all to understand what we are willing to sacrifice to have even just one
more sword, one more spear, one more arrow, one more dagger..."

One thing must now be made clear to you.

Each clan has their customs and traditions. Ways of marking time and the
seasons. Ways of showing the world their family ties. In some clans this is done
through tattoos, or piercings, or specific hair styles. In the Oda Clan, your
hair was your connection to your clan. Elaborate braids, each with secret
meaning, bound up each Oda Clan members hair, starting when they reached the age
of majority.

Oda Kina Uma Shire's braid was 6 feet long, and she looped it around her neck
almost like a scarf to keep it off the ground.

Her braid was a story of a long life, well lived.

She took hold of the Sword of Jade in one hand, and gripped her braid near the
base -- and cut off the entire braid with the sword.

She held it out, and slowly turned. This time, every member in the crowd felt as
if she stared directly into their soul.

After she had completed her rotation, she dropped the braid before her. At this
point, those close enough to see the rest of the Oda clan realized they were all
holding their braids. In their other hands they held daggers. Even the youngest
of the clan stood ready.

Oda Kina Uma Shire tapped the sword on the pillar one last time. When she did,
every member of the Oda Clan cut off their braid.

"I am now Uma Shire. Without family. Without clan. My family marches to war, my
clan is dead. The Oda are no more. They died as the Khan did: delivering a message.

This is the truth we beg you to understand. This is how important we feel this
is. It is bigger than family. Bigger than clan.

Please. Come with us.

Face this invader. Tell them that to take this land, they need to take it from
all of us. That so long as one of us stands, this land will never be theirs!
That so long as one of draws breath, they will have to fight for every step they
take!

We will etch a story of blood and destruction into their souls so final that
their name will be lost to history.

The gods will turn from them in horror, for we will mark them with every rune of
aversion we know.

The winds will never stir their fields, the rain will never quench their thirst,
their crops will never grow in the lands we deny to them with every drop of
blood we have.

Come with us, as we go to commit total war.

Come with us, and avenge the Khan and the Oda."

Besides the wind, there was no sound.

For a full minute, nobody spoke. Nobody knew what to say.

At last, a woman near the now clanless warriors stood.

"I am Ibahka Togh Kira Sun. I grieve for the Khan. I grieve for the Oda. I will
fight. I will avenge. I will ensure no more clans die."

After that, the dam had been broken. They believed.

All of the clans marched to war, and met the abhumans on the field. Some say it
was one of the Oda who sacrificed themselves to become the First
Defender. Others say it was Ibahka Togh Kira Sun. Nearly every clan believes it
was one of them who sacrificed themselves to complete the revenge of the Khan
and the Oda.

Whatever the case may be, that is how the clans came together to become the
people of Sudboia, how the Clan of Clans came to be.

To this day, we pay respect to the clans that died.

The Khans live on, remembered in the title we give our ruler: Sudkhan -- an
ancient way of saying "Avenger of the Khan".

We remember the Oda too: their sacrifice to bring the clans together is the laws
and bonds that hold us together as Sudboia; the laws we follow are laid down in
the Odakioda. Another ancient way of saying something, meaning "Words of the
Oda".

It is through their sacrifice and guidance that the clans are still around
today, their ancestors guiding us all.
