* The Lost Daughter
:PROPERTIES:
:ID:       82727b0d-41a4-401d-940c-c87c4fbbc04e
:END:
1: Around 80 years ago, the Sudkhan Kell starting what he hoped would be his
final term as Sacred Protector. He had spent several lifetimes protecting
Sudboia, and wanted to spend some time back in the saddle, exploring the
land. His blessing and curse of long life meant that he wanted to try to go out
and experience things instead of being stuck in this role forever.

2: So he hoped to turn the mantle over to his daughter, Ibakha Togh Shaho. She was
a strong and confident woman, more than capable of leading the clans -- whether
into battle or into a new era of prosperity, she could handle it.

3: Then one day a stranger came to the clans. He said he was from a land far to the
South, and he had spent his life traveling. His feet had led him to Sudboia, and
he wished to learn of their customs and culture if they would let him.

4: Most clans were fine with this; welcoming outsiders temporarily into your clan
is an important tradition to Sudboians. A stranger you help today could save
your life tomorrow, as the saying goes. So the stranger joined the Ika clan, and
spent a year with them.

5: He shared his name; Acastus Skips. He shared some of his talents and knowledge
with the Ika clan. He helped the hunters bring home food, and helped watch over
livestock. He helped care for the sick, and taught the children some stories and
lessons.

6: After a while, Acastus decided he had learned all he could from the Ika, and
moved on. He spent a few years, drifting from clan to clan, learning and sharing
knowledge and skills.

7: After five years, enough stories of the Stranger from the South had reached
Sudkhan Kell that they had grown curious. He sent a messenger to find Acastus
and invite him to stay with the Sudkhan for a while. Eventually, the messenger
returned with Acastus Skips and presented him to the Sudkhan.

8: By this time, Acastus had learned much from the clans; he presented himself in
the proper manner to the Sudkhan and asked permission to remain in the presence
of the Sacred Defender.

9: Delighted by this outsiders proper use of their customs, the Sudkhan decided
that he could dispense with all the formalities. Removing his bracers and
choi-ha ( akin to a headband with bits of stamped metal woven into it ) and sat
on the ground before his chieftans chair and indicated for Acastus to sit as
well.

10: "You have done well to learn our customs, even our language, Acastus
Skips. However, learning is hindered by screens and shields of the traditions we
cloak ourselves with. While it is important to maintain those traditions, when
learning I have found it best to remove any distractions or hindrances."

11: Grinning, Acastus lowered himself to the floor to sit cross-legged.

"I completely understand and agree, Sudkhan. If only those I have dealt with in
the past were as wise as yourself."

12: And so the Sudkhan and Acastus sat and spoke for many hours. Acastus shared
tales of where he had been, and what he had learned. The Sudkhan explained his
role as Sacred Defender, and shared some of the history of Sudboia.

Eventually, the dinner bell was rung. The Sudkhan invited Acastus to dine with
him and his family, which Acastus graciously agreed to.

13: While other rulers may insist on only feasting upon the finest foods and wines,
Sudboians are different. We don't trust leaders who drink from gilded goblets
while the majority of their people live in dirt. Our leaders eat as we do, sleep
as we do, and shit as we do. So although they may have more finery than a
few clan chiefs put together, they still understand they are not kings or gods;
they are first among clan chiefs. Not above the clan chiefs, or the clans, or
any of us.

14: So rather than the fine delicacies he had experienced from nobles and merchants
he had met in the past, at the table of the Sudkhan he ate the same foods he had
been eating when among the clans. It is said that Acastus Skips praised the
Sudkhan and all Sudboia for figuring out how to ensure a leader doesn't grow to
think of themselves as a god, or worse.

15: After the meal, Acastus agreed to stay with the Sudkhan for a time. He would
share his knowledge of the wider world, both it's dangers and wonders. In
return, the Sudkhan would share more about the history & people of
Sudboia. While we Sudboians think our culture works pretty well, we still know
there's always room for improvement.

16:The arangement worked fine for several months.

Then one day, Acastus was gone. Also gone was Ibakha Togh Shaho, the daughter of
the Sudkhan.

All that was left behind was a note from Shaho.

17: It spoke of wanting to see the world, and to not be weighed down by the
expectations and responsibilities of Sacred Defender, or Sudkhan. She wanted to
find somewhere to live where she could just be herself, not a Togh, not a
Ibakha, just Shaho. She had left with Acastus because he was her best chance to
leave not just her clan, but all of Sudboia. She was sorry, but knew her destiny
lay outside the plains of the Clans.

Sudkhan Kell was furious. He felt betrayed, not only by Acastus, but by his own
daughter.

18: He resolved that if he couldn't trust his own flesh and blood to take up the
mantle, nobody else would. He would ensure that all of Sudboia was safe and
prosperous, and free of the treacheries of outsiders like Acastus.

19: Neither Ibahka Togh Shaho nor Acastus Skips was ever seen again. Nobody knows
how they left Sudboia without being seen by anyone.

20: Some claim Acastus was a devil or evil spirit, sent to try and corrupt the clans
to wicked ways. Others say he was just a man who fell in love and agreed to do
something stupid because of it.

21: Nobody knows why they ran off, but as the legend grows we should remember that
the story isn't over yet. Sudkhan Kell still leads us, and we are grateful to
have a wise leader who can see past today and to where the Clans need to go in
the future.
