* Rulings
** Helping
if you want to help someone when they're trying to accomplish a task, you have
to be untrained or better ( remember, skills can be inability -> untrained ->
trained -> specialized, from worst to best ). if you're untrained, you ease the
task by one step. if you're trained or specialized, you ease the task by two
steps.

however: when performing a task you can only ease the difficulty by two steps
using an asset, and help from other characters is considered an asset. so two
untrained people can help, or one person who is trained or specialized can help.

keep in mind though, that the really difficult tasks you encounter in the world
have many solutions, or potentially many steps. for example, say you find a
weapon emplacement that you need to fire at the enemy to break through the walls
of their fort. say Zeno decides he's going to take control of the machine to
take the shot. the rest of the party can try to help, but the most they can do
is reduce the difficulty by two. but that's not the only thing you could
do. maybe if you've got time, one of the nanos can try and change the settings
of the weapons interface so it's in a language Zeno understands. maybe there's a
device nearby that would give you precise distance & environment measurements
that would make the weapon more accurate, but you've got to figure out the
password or bypass the security to enable it. or something else that i can't
think of right now.

hint you could even use 1 XP for a player intrusion to come up with those
suggestions i made above, or think up your own -- it's something we can discuss
and hammer out the details during game.
** Healing
1. If you go down the damage track due to losing all the points in a pool,
   healing 1 or more points to an empty pool moves you back up the damage track

2. If you go down the damage track due to an attack that damages your PC in that
   fashion, only a recovery roll will move you back up the damage track

3. Cyphers and abilities that restore points to a pool will not move you back up
   the damage track ( unless covered by point 1 )

4. However, if a cypher or ability specifically refers to a recovery roll (
   providing the same benefits as a recovery roll without using up one from your
   sheet ), then it will move you up the damage track

5. going up a level on the damage track is a level 4 or 6 difficulty task
   depending on if the character is impaired or debilitated

6. healing points in a pool is an intellect task with the difficulty equal to
   how many points they're trying to heal
** Weapon Modifiers
*** Reach
 - eases attacks vs opponents without reach
 - hinders attacks vs opponents within immediate range
*** Entangle
May be used to inflict damage, or it may be used to stun a creature with a level
of the weapon's damage or less (attack roll required every round to maintain
effect, miss means the target gets free and may act normally). Higher level
creatures may be entangled by using effort to increase 'damage', however to
maintain the effect Effort must be spent every turn.

* To Decide
