languageCode: en-us
title: Sean's Campaign Notes
theme: hugo-theme-anubis
languageCode: en-us
publishDir: _site
enableGitInfo: true
enableRobotsTXT: true

# menu:
#   main:
#   - identifier: pages
#     name: Pages
#     title: Pages
#     url: /pages/
#     weight: 0

params:
  author: "Sean Hagen"
  email: sean.hagen@gmail.com # used for microformats
  description: "Campaign notes from my ongoing campaigns"
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: dark-without-switcher
  readMore: false
  disableSummary: true
  # utteranc.es support
  # utterancesRepo: ""  # mandatory
  # utterancesTheme: "" # optional
  # utterancesIssue: "" # optional
  # utterancesLabel: "" # optional
  # webmentions:
  #   url: https://yourdomain.com/webemntions/receive
  #   login: hugo-theme-anubis
  #   pingback: true
  # social:
  # - id: github
  #   name: gohugoio
#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown

